---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: watcher-{{.Iteration}}-{{.Replica}}
spec:
  replicas: {{.podReplicas}}
  selector:
    matchLabels:
      name: watcher-{{.Iteration}}-{{.Replica}}
  template:
    metadata:
      labels:
        name: watcher-{{.Iteration}}-{{.Replica}}
        app: watcher-{{.Iteration}}-{{.Replica}}
    spec:
      containers:
      {{$data := .}}
      {{range until .containerCount}}
      - name: watcher-{{.}}
        image: quay.io/akrzos/occli:latest
        command:
        - /bin/bash
        - -c
        - |
          # echo "Start watching all pods"
          # while true; do
          #   oc get po -A -w
          #   echo "Watching all pods"
          # done
          echo "Start watching all hcpworkloads0"
          while true; do
            oc get hcpworkloads0 -A -w
            echo "Watching all hcpworkloads0"
          done
        resources:
          requests:
            memory: "35Mi"
            cpu: "2m"
        volumeMounts:
        - name: secret-kc
          mountPath: /opt
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBECONFIG
          value: "/opt/kubeconfig"
      {{end}}
      volumes:
      - name: secret-kc
        secret:
          secretName: kubeconfig
      nodeSelector:
      {{range .nodeSelector}}
        {{.}}
      {{end}}
      tolerations:
      {{range .tolerations}}
      - key: "{{.key}}"
        operator: "{{.operator}}"
        effect: "{{.effect}}"
      {{end}}
