---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: client-{{.Replica}}
spec:
  replicas: {{.podReplicas}}
  selector:
    matchLabels:
      name: client-{{.Replica}}
  template:
    metadata:
      labels:
        name: client-{{.Replica}}
        app: client
    spec:
      containers:
      - name: client-app
        image: quay.io/cloud-bulldozer/curl:latest
        command: ["sleep", "inf"]
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
        volumeMounts:
        - name: secret-1
          mountPath: /secret1
        - name: configmap-1
          mountPath: /configmap1
        - name: podinfo
          mountPath: /etc/podlabels
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "curl --fail -sS ${SERVICE_ENDPOINT} -o /dev/null"
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: ENVVAR1
          value: "{{randAlphaNum 250}}"
        - name: SERVICE_ENDPOINT
          value: "http://hcp-rate-1/256.html"
      volumes:
      - name: secret-1
        secret:
          secretName: {{.JobName}}-1
      - name: configmap-1
        configMap:
          name: {{.JobName}}-1
      - name: podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
