---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: client-{{.Iteration}}-{{.Replica}}
spec:
  replicas: {{.podReplicas}}
  selector:
    matchLabels:
      name: client-{{.Iteration}}-{{.Replica}}
  template:
    metadata:
      labels:
        name: client-{{.Iteration}}-{{.Replica}}
        app: client
        {{range until .labelCount}}
        label{{.}}: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        {{end}}
    spec:
      containers:
      {{$data := .}}
      {{range until .containerCount}}
      - name: client-{{.}}
        image: quay.io/cloud-bulldozer/curl:latest
        command: ["sleep", "inf"]
        resources:
          requests:
            memory: "2Mi"
            cpu: "5m"
        volumeMounts:
        {{range until $data.secrets}}
        - name: secret-{{.}}
          mountPath: /secret{{.}}
        {{end}}
        {{range until $data.configmaps}}
        - name: cm-{{.}}
          mountPath: /configmap{{.}}
        {{end}}
        - name: podinfo
          mountPath: /etc/podlabels
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "curl --fail -sS ${SERVICE_ENDPOINT} -o /dev/null"
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        {{$r_index := add $data.Replica -1}}
        - name: SERVICE_ENDPOINT
          value: "http://server-{{$data.Iteration}}-{{mod $r_index $data.servicePerDeploy | add1}}:{{add $data.serviceStartPort .}}/home"
        {{range until $data.envAddVarCount}}
        - name: ENVVAR_{{.}}
          value: "{{randAlphaNum $data.envAddVarSize}}"
        {{end}}
      {{end}}
      volumes:
      {{range until .secrets}}
      {{$r_index := add $data.Replica -1}}
      {{$d_s_count := mul $r_index $data.secrets}}
      {{$s_index := add $d_s_count . 1}}
      - name: secret-{{.}}
        secret:
          secretName: server-{{$data.Iteration}}-{{$s_index}}
      {{end}}
      {{range until .configmaps}}
      {{$r_index := add $data.Replica -1}}
      {{$d_cm_count := mul $r_index $data.configmaps}}
      {{$cm_index := add $d_cm_count . 1}}
      - name: cm-{{.}}
        configMap:
          name: server-{{$data.Iteration}}-{{$cm_index}}
      {{end}}
      - name: podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
