---
global:
  gc: false
metricsEndpoints:
{{if .ES_SERVER}}
- metrics: [hcp-workload/metrics-profile/metrics.yml, hcp-workload/metrics-profile/metrics-report.yml]
  alerts: [hcp-workload/alerts.yml]
  indexer:
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{.ES_INDEX}}
    type: opensearch
{{if .PROM_URL}}
  endpoint: {{.PROM_URL}}
  token: {{.PROM_TOKEN}}
{{end}}
{{end}}
{{if .LOCAL_INDEXING }}
- metrics: [hcp-workload/metrics-profile/metrics.yml, hcp-workload/metrics-profile/metrics-report.yml]
  alerts: [hcp-workload/alerts.yml]
  indexer:
    type: local
    metricsDirectory: {{.METRICS_DIRECTORY}}
{{if .PROM_URL}}
  endpoint: {{.PROM_URL}}
  token: {{.PROM_TOKEN}}
{{end}}
{{end}}

jobs:
{{$data := .}}
{{range until (.STEPS | int)}}
- name: ramp-cm-{{.}}
  jobType: create
  jobIterations: {{$data.ITERATIONS}}
  namespace: hcp-workload
  namespacedIterations: true
  podWait: false
  waitWhenFinished: false
  verifyObjects: false
  jobPause: {{$data.JOB_PAUSE_TIME}}
  qps: {{$data.QPS}}
  burst: {{$data.BURST}}
  preLoadImages: false
  preLoadPeriod: 1m
  namespaceLabels:
    security.openshift.io/scc.podSecurityLabelSync: false
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    hcp-workload: true
  objects:
  - objectTemplate: hcp-workload/configmap.yml
    replicas: {{$data.CONFIGMAPS}}
    inputVars:
      cmPrefix: ramp{{.}}
      cmKeyCount: {{$data.CM_KEY_COUNT}}
      cmValueSize: {{$data.CM_VALUE_SIZE}}
{{end}}
