---
global:
  gc: true

jobs:
- name: cleanup-hcp-workload
  jobType: delete
  waitForDeletion: true
  qps: 10
  burst: 20
  objects:
  - kind: Namespace
    labelSelector:
      kube-burner.io/job: hcp-workload
    apiVersion: v1
{{if eq .CLEANUP_CRDS "true"}}
  - kind: CustomResourceDefinition
    labelSelector:
      kube-burner.io/job: hcp-workload-crd
    apiVersion: apiextensions.k8s.io/v1
{{end}}
