---
global:
  gc: false

jobs:
- name: hcp-workload-crd
  jobType: create
  jobIterations: {{.CRDS}}
  namespacedIterations: false
  cleanup: false
  podWait: false
  qps: {{.QPS}}
  burst: {{.BURST}}
  objects:
  - objectTemplate: hcp-workload/crd-hcpworkload.yml
    replicas: 1
