---
apiVersion: v1
kind: Secret
metadata:
  name: server-{{.Iteration}}-{{.Replica}}
data:
  {{$data := .}}
  {{range until .secretKeyCount}}
  key{{.}}: {{randAlphaNum $data.secretValueSize}}
  {{end}}
