---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |+
    prometheusK8s:
      retention: 15d
      volumeClaimTemplate:
        metadata:
          name: localpvc
        spec:
          storageClassName: localstorage-sc
          resources:
            requests:
              storage: 50Gi
