---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-stress
  namespace: vpa-stress
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stress
  updatePolicy:
    updateMode: "Off"
